development:
  adapter: postgresql
  encoding: utf-8
  database: navin_bank #lbr_jsonb_local3 #nine_dot_nine_sep19
  host: localhost
  username: saawan
  password: saawan!1234
  port: 5432

production:
  adapter: postgresql
  encoding: utf-8
  database: navin_bank #lbr_jsonb_local3 #nine_dot_nine_sep19
  host: localhost
  username: abc
  password: anupamaanu
  port: 5432

test:
  adapter: postgresql
  encoding: utf-8
  database: navinbank_test #lbr_jsonb_local3 #nine_dot_nine_sep19
  host: localhost
  username: saawan
  password: saawan!1234
  port: 5432